// 이모티콘 SVG 불러오기
// @ts-ignore
import JoyEmoji from './assets/icons/JoyEmoji';
// @ts-ignore
import CalmEmoji from './assets/icons/CalmEmoji';
// @ts-ignore
import SadEmoji from './assets/icons/SadEmoji';
// @ts-ignore
import AngryEmoji from './assets/icons/AngryEmoji';
// @ts-ignore
import AnxiousEmoji from './assets/icons/AnxiousEmoji';
// @ts-ignore
import CryingEmoji from './assets/icons/CryingEmoji';

export const EMOTIONS = [
  { id: 'joy', color: '#FF5B5B', icon: JoyEmoji },
  { id: 'calm', color: '#64E671', icon: CalmEmoji },
  { id: 'sadness', color: '#FFB661', icon: SadEmoji },
  { id: 'anger', color: '#FFD25E', icon: AngryEmoji },
  { id: 'anxiety', color: '#FF6187', icon: AnxiousEmoji },
  { id: 'crying', color: '#E961FF', icon: CryingEmoji },
];

export const BACKGROUNDS = [
  { id: '#ffffff', color: '#ffffff', name: '화이트' },
  { id: '#fff9e6', color: '#fff9e6', name: '아이보리' },
  { id: '#ffe5ec', color: '#ffe5ec', name: '딸기우유' },
  { id: '#f0f8ff', color: '#f0f8ff', name: '스카이' },
  { id: '#e6e6fa', color: '#e6e6fa', name: '라벤더' },
  { id: '#e8f5e9', color: '#e8f5e9', name: '민트그린' },
  { id: 'grid', color: '#ffffff', name: '모눈격자' }, 
];

export const STICKER_CATEGORIES = {
  '생일/파티': [
    { id: 'birth1_01', type: 'image', source: require('./assets/stickers/birth1/birth1_01.png') },
    { id: 'birth1_02', type: 'image', source: require('./assets/stickers/birth1/birth1_02.png') },
    { id: 'birth1_03', type: 'image', source: require('./assets/stickers/birth1/birth1_03.png') },
    { id: 'birth1_04', type: 'image', source: require('./assets/stickers/birth1/birth1_04.png') },
    { id: 'birth1_05', type: 'image', source: require('./assets/stickers/birth1/birth1_05.png') },
    { id: 'birth1_06', type: 'image', source: require('./assets/stickers/birth1/birth1_06.png') },
    { id: 'birth1_07', type: 'image', source: require('./assets/stickers/birth1/birth1_07.png') },
    { id: 'birth1_08', type: 'image', source: require('./assets/stickers/birth1/birth1_08.png') },
    { id: 'birth1_09', type: 'image', source: require('./assets/stickers/birth1/birth1_09.png') },
    { id: 'birth1_10', type: 'image', source: require('./assets/stickers/birth1/birth1_10.png') },
    { id: 'birth1_11', type: 'image', source: require('./assets/stickers/birth1/birth1_11.png') },
    { id: 'birth1_12', type: 'image', source: require('./assets/stickers/birth1/birth1_12.png') },
    { id: 'birth1_13', type: 'image', source: require('./assets/stickers/birth1/birth1_13.png') }
  ],
  '자연/날씨': [
    { id: 'clou1_01', type: 'image', source: require('./assets/stickers/clou1/clou1_01.png') },
    { id: 'clou1_02', type: 'image', source: require('./assets/stickers/clou1/clou1_02.png') },
    { id: 'clou1_03', type: 'image', source: require('./assets/stickers/clou1/clou1_03.png') },
    { id: 'clou1_04', type: 'image', source: require('./assets/stickers/clou1/clou1_04.png') },
    { id: 'clou1_05', type: 'image', source: require('./assets/stickers/clou1/clou1_05.png') },
    { id: 'clou1_06', type: 'image', source: require('./assets/stickers/clou1/clou1_06.png') },
    { id: 'clou1_07', type: 'image', source: require('./assets/stickers/clou1/clou1_07.png') },
    { id: 'clou1_08', type: 'image', source: require('./assets/stickers/clou1/clou1_08.png') },
    { id: 'clou1_09', type: 'image', source: require('./assets/stickers/clou1/clou1_09.png') },
    { id: 'clou1_10', type: 'image', source: require('./assets/stickers/clou1/clou1_10.png') },
    { id: 'clou1_11', type: 'image', source: require('./assets/stickers/clou1/clou1_11.png') },
    { id: 'clou1_12', type: 'image', source: require('./assets/stickers/clou1/clou1_12.png') },
    { id: 'fire1_01', type: 'image', source: require('./assets/stickers/fire1/fire1_01.png') },
    { id: 'fire1_02', type: 'image', source: require('./assets/stickers/fire1/fire1_02.png') },
    { id: 'fire1_03', type: 'image', source: require('./assets/stickers/fire1/fire1_03.png') },
    { id: 'fire1_04', type: 'image', source: require('./assets/stickers/fire1/fire1_04.png') },
    { id: 'fire1_05', type: 'image', source: require('./assets/stickers/fire1/fire1_05.png') },
    { id: 'fire1_06', type: 'image', source: require('./assets/stickers/fire1/fire1_06.png') },
    { id: 'fire1_07', type: 'image', source: require('./assets/stickers/fire1/fire1_07.png') },
    { id: 'fire1_08', type: 'image', source: require('./assets/stickers/fire1/fire1_08.png') },
    { id: 'fire1_09', type: 'image', source: require('./assets/stickers/fire1/fire1_09.png') },
    { id: 'fire1_10', type: 'image', source: require('./assets/stickers/fire1/fire1_10.png') },
    { id: 'fire1_11', type: 'image', source: require('./assets/stickers/fire1/fire1_11.png') },
    { id: 'fire1_12', type: 'image', source: require('./assets/stickers/fire1/fire1_12.png') },
    { id: 'flower1_01', type: 'image', source: require('./assets/stickers/flower1/flower1_01.png') },
    { id: 'flower1_02', type: 'image', source: require('./assets/stickers/flower1/flower1_02.png') },
    { id: 'flower1_03', type: 'image', source: require('./assets/stickers/flower1/flower1_03.png') },
    { id: 'flower1_04', type: 'image', source: require('./assets/stickers/flower1/flower1_04.png') },
    { id: 'flower1_05', type: 'image', source: require('./assets/stickers/flower1/flower1_05.png') },
    { id: 'flower1_06', type: 'image', source: require('./assets/stickers/flower1/flower1_06.png') },
    { id: 'flower1_07', type: 'image', source: require('./assets/stickers/flower1/flower1_07.png') },
    { id: 'flower1_08', type: 'image', source: require('./assets/stickers/flower1/flower1_08.png') },
    { id: 'flower1_09', type: 'image', source: require('./assets/stickers/flower1/flower1_09.png') },
    { id: 'flower1_10', type: 'image', source: require('./assets/stickers/flower1/flower1_10.png') },
    { id: 'flower1_11', type: 'image', source: require('./assets/stickers/flower1/flower1_11.png') },
    { id: 'flower1_12', type: 'image', source: require('./assets/stickers/flower1/flower1_12.png') },
    { id: 'light1_01', type: 'image', source: require('./assets/stickers/light1/light1_01.png') },
    { id: 'light1_02', type: 'image', source: require('./assets/stickers/light1/light1_02.png') },
    { id: 'light1_03', type: 'image', source: require('./assets/stickers/light1/light1_03.png') },
    { id: 'light1_04', type: 'image', source: require('./assets/stickers/light1/light1_04.png') },
    { id: 'light1_05', type: 'image', source: require('./assets/stickers/light1/light1_05.png') },
    { id: 'light1_06', type: 'image', source: require('./assets/stickers/light1/light1_06.png') },
    { id: 'light1_07', type: 'image', source: require('./assets/stickers/light1/light1_07.png') },
    { id: 'light1_08', type: 'image', source: require('./assets/stickers/light1/light1_08.png') },
    { id: 'light1_09', type: 'image', source: require('./assets/stickers/light1/light1_09.png') },
    { id: 'light1_10', type: 'image', source: require('./assets/stickers/light1/light1_10.png') },
    { id: 'light1_11', type: 'image', source: require('./assets/stickers/light1/light1_11.png') },
    { id: 'light1_12', type: 'image', source: require('./assets/stickers/light1/light1_12.png') },
    { id: 'moon1_01', type: 'image', source: require('./assets/stickers/moon1/moon1_01.png') },
    { id: 'moon1_02', type: 'image', source: require('./assets/stickers/moon1/moon1_02.png') },
    { id: 'moon1_03', type: 'image', source: require('./assets/stickers/moon1/moon1_03.png') },
    { id: 'moon1_04', type: 'image', source: require('./assets/stickers/moon1/moon1_04.png') },
    { id: 'moon1_05', type: 'image', source: require('./assets/stickers/moon1/moon1_05.png') },
    { id: 'moon1_06', type: 'image', source: require('./assets/stickers/moon1/moon1_06.png') },
    { id: 'moon1_07', type: 'image', source: require('./assets/stickers/moon1/moon1_07.png') },
    { id: 'moon1_08', type: 'image', source: require('./assets/stickers/moon1/moon1_08.png') },
    { id: 'moon1_09', type: 'image', source: require('./assets/stickers/moon1/moon1_09.png') },
    { id: 'moon1_10', type: 'image', source: require('./assets/stickers/moon1/moon1_10.png') },
    { id: 'moon1_11', type: 'image', source: require('./assets/stickers/moon1/moon1_11.png') },
    { id: 'moon1_12', type: 'image', source: require('./assets/stickers/moon1/moon1_12.png') },
    { id: 'star1_01', type: 'image', source: require('./assets/stickers/star1/star1_01.png') },
    { id: 'star1_02', type: 'image', source: require('./assets/stickers/star1/star1_02.png') },
    { id: 'star1_03', type: 'image', source: require('./assets/stickers/star1/star1_03.png') },
    { id: 'star1_04', type: 'image', source: require('./assets/stickers/star1/star1_04.png') },
    { id: 'star1_05', type: 'image', source: require('./assets/stickers/star1/star1_05.png') },
    { id: 'star1_06', type: 'image', source: require('./assets/stickers/star1/star1_06.png') },
    { id: 'star1_07', type: 'image', source: require('./assets/stickers/star1/star1_07.png') },
    { id: 'star1_08', type: 'image', source: require('./assets/stickers/star1/star1_08.png') },
    { id: 'star1_09', type: 'image', source: require('./assets/stickers/star1/star1_09.png') },
    { id: 'star1_10', type: 'image', source: require('./assets/stickers/star1/star1_10.png') },
    { id: 'star1_11', type: 'image', source: require('./assets/stickers/star1/star1_11.png') },
    { id: 'star1_12', type: 'image', source: require('./assets/stickers/star1/star1_12.png') }
  ],
  '푸드/소풍': [
    { id: 'coffee_01', type: 'image', source: require('./assets/stickers/coffee/coffee_01.png') },
    { id: 'coffee_02', type: 'image', source: require('./assets/stickers/coffee/coffee_02.png') },
    { id: 'coffee_03', type: 'image', source: require('./assets/stickers/coffee/coffee_03.png') },
    { id: 'coffee_04', type: 'image', source: require('./assets/stickers/coffee/coffee_04.png') },
    { id: 'coffee_05', type: 'image', source: require('./assets/stickers/coffee/coffee_05.png') },
    { id: 'coffee_06', type: 'image', source: require('./assets/stickers/coffee/coffee_06.png') },
    { id: 'coffee_07', type: 'image', source: require('./assets/stickers/coffee/coffee_07.png') },
    { id: 'coffee_08', type: 'image', source: require('./assets/stickers/coffee/coffee_08.png') },
    { id: 'coffee_09', type: 'image', source: require('./assets/stickers/coffee/coffee_09.png') },
    { id: 'coffee_10', type: 'image', source: require('./assets/stickers/coffee/coffee_10.png') },
    { id: 'coffee_11', type: 'image', source: require('./assets/stickers/coffee/coffee_11.png') },
    { id: 'coffee_12', type: 'image', source: require('./assets/stickers/coffee/coffee_12.png') },
    { id: 'fruit1_01', type: 'image', source: require('./assets/stickers/fruit1/fruit1_01.png') },
    { id: 'fruit1_02', type: 'image', source: require('./assets/stickers/fruit1/fruit1_02.png') },
    { id: 'fruit1_03', type: 'image', source: require('./assets/stickers/fruit1/fruit1_03.png') },
    { id: 'fruit1_04', type: 'image', source: require('./assets/stickers/fruit1/fruit1_04.png') },
    { id: 'fruit1_05', type: 'image', source: require('./assets/stickers/fruit1/fruit1_05.png') },
    { id: 'fruit1_06', type: 'image', source: require('./assets/stickers/fruit1/fruit1_06.png') },
    { id: 'fruit1_07', type: 'image', source: require('./assets/stickers/fruit1/fruit1_07.png') },
    { id: 'fruit1_08', type: 'image', source: require('./assets/stickers/fruit1/fruit1_08.png') },
    { id: 'fruit1_09', type: 'image', source: require('./assets/stickers/fruit1/fruit1_09.png') },
    { id: 'fruit1_10', type: 'image', source: require('./assets/stickers/fruit1/fruit1_10.png') },
    { id: 'fruit1_11', type: 'image', source: require('./assets/stickers/fruit1/fruit1_11.png') },
    { id: 'fruit1_12', type: 'image', source: require('./assets/stickers/fruit1/fruit1_12.png') },
    { id: 'picnic_01', type: 'image', source: require('./assets/stickers/picnic/picnic_01.png') },
    { id: 'picnic_02', type: 'image', source: require('./assets/stickers/picnic/picnic_02.png') },
    { id: 'picnic_03', type: 'image', source: require('./assets/stickers/picnic/picnic_03.png') },
    { id: 'picnic_04', type: 'image', source: require('./assets/stickers/picnic/picnic_04.png') },
    { id: 'picnic_05', type: 'image', source: require('./assets/stickers/picnic/picnic_05.png') },
    { id: 'picnic_06', type: 'image', source: require('./assets/stickers/picnic/picnic_06.png') },
    { id: 'picnic_07', type: 'image', source: require('./assets/stickers/picnic/picnic_07.png') },
    { id: 'picnic_08', type: 'image', source: require('./assets/stickers/picnic/picnic_08.png') },
    { id: 'picnic_09', type: 'image', source: require('./assets/stickers/picnic/picnic_09.png') },
    { id: 'picnic_10', type: 'image', source: require('./assets/stickers/picnic/picnic_10.png') },
    { id: 'picnic_11', type: 'image', source: require('./assets/stickers/picnic/picnic_11.png') },
    { id: 'picnic_12', type: 'image', source: require('./assets/stickers/picnic/picnic_12.png') }
  ],
  '감성/무드': [
    { id: 'pink1_01', type: 'image', source: require('./assets/stickers/pink1/pink1_01.png') },
    { id: 'pink1_02', type: 'image', source: require('./assets/stickers/pink1/pink1_02.png') },
    { id: 'pink1_03', type: 'image', source: require('./assets/stickers/pink1/pink1_03.png') },
    { id: 'pink1_04', type: 'image', source: require('./assets/stickers/pink1/pink1_04.png') },
    { id: 'pink1_05', type: 'image', source: require('./assets/stickers/pink1/pink1_05.png') },
    { id: 'pink1_06', type: 'image', source: require('./assets/stickers/pink1/pink1_06.png') },
    { id: 'pink1_07', type: 'image', source: require('./assets/stickers/pink1/pink1_07.png') },
    { id: 'pink1_08', type: 'image', source: require('./assets/stickers/pink1/pink1_08.png') },
    { id: 'pink1_09', type: 'image', source: require('./assets/stickers/pink1/pink1_09.png') },
    { id: 'pink1_10', type: 'image', source: require('./assets/stickers/pink1/pink1_10.png') },
    { id: 'pink1_11', type: 'image', source: require('./assets/stickers/pink1/pink1_11.png') },
    { id: 'pink1_12', type: 'image', source: require('./assets/stickers/pink1/pink1_12.png') },
    { id: 'pink1_13', type: 'image', source: require('./assets/stickers/pink1/pink1_13.png') },
    { id: 'pink1_14', type: 'image', source: require('./assets/stickers/pink1/pink1_14.png') },
    { id: 'pink1_15', type: 'image', source: require('./assets/stickers/pink1/pink1_15.png') },
    { id: 'pink1_16', type: 'image', source: require('./assets/stickers/pink1/pink1_16.png') },
    { id: 'pink1_17', type: 'image', source: require('./assets/stickers/pink1/pink1_17.png') },
    { id: 'pink1_18', type: 'image', source: require('./assets/stickers/pink1/pink1_18.png') },
    { id: 'pink1_19', type: 'image', source: require('./assets/stickers/pink1/pink1_19.png') },
    { id: 'pink1_20', type: 'image', source: require('./assets/stickers/pink1/pink1_20.png') },
    { id: 'pink1_21', type: 'image', source: require('./assets/stickers/pink1/pink1_21.png') },
    { id: 'pink1_22', type: 'image', source: require('./assets/stickers/pink1/pink1_22.png') },
    { id: 'pink1_23', type: 'image', source: require('./assets/stickers/pink1/pink1_23.png') },
    { id: 'pink1_24', type: 'image', source: require('./assets/stickers/pink1/pink1_24.png') },
    { id: 'pink1_25', type: 'image', source: require('./assets/stickers/pink1/pink1_25.png') },
    { id: 'purple1_01', type: 'image', source: require('./assets/stickers/purple1/purple1_01.png') },
    { id: 'purple1_02', type: 'image', source: require('./assets/stickers/purple1/purple1_02.png') },
    { id: 'purple1_03', type: 'image', source: require('./assets/stickers/purple1/purple1_03.png') },
    { id: 'purple1_04', type: 'image', source: require('./assets/stickers/purple1/purple1_04.png') },
    { id: 'purple1_05', type: 'image', source: require('./assets/stickers/purple1/purple1_05.png') },
    { id: 'purple1_06', type: 'image', source: require('./assets/stickers/purple1/purple1_06.png') },
    { id: 'purple1_07', type: 'image', source: require('./assets/stickers/purple1/purple1_07.png') },
    { id: 'purple1_08', type: 'image', source: require('./assets/stickers/purple1/purple1_08.png') },
    { id: 'purple1_09', type: 'image', source: require('./assets/stickers/purple1/purple1_09.png') },
    { id: 'purple1_10', type: 'image', source: require('./assets/stickers/purple1/purple1_10.png') },
    { id: 'purple1_11', type: 'image', source: require('./assets/stickers/purple1/purple1_11.png') },
    { id: 'purple1_12', type: 'image', source: require('./assets/stickers/purple1/purple1_12.png') },
    { id: 'romance1_01', type: 'image', source: require('./assets/stickers/romance1/romance1_01.png') },
    { id: 'romance1_02', type: 'image', source: require('./assets/stickers/romance1/romance1_02.png') },
    { id: 'romance1_03', type: 'image', source: require('./assets/stickers/romance1/romance1_03.png') },
    { id: 'romance1_04', type: 'image', source: require('./assets/stickers/romance1/romance1_04.png') },
    { id: 'romance1_05', type: 'image', source: require('./assets/stickers/romance1/romance1_05.png') },
    { id: 'romance1_06', type: 'image', source: require('./assets/stickers/romance1/romance1_06.png') },
    { id: 'romance1_07', type: 'image', source: require('./assets/stickers/romance1/romance1_07.png') },
    { id: 'romance1_08', type: 'image', source: require('./assets/stickers/romance1/romance1_08.png') },
    { id: 'romance1_09', type: 'image', source: require('./assets/stickers/romance1/romance1_09.png') },
    { id: 'romance1_10', type: 'image', source: require('./assets/stickers/romance1/romance1_10.png') },
    { id: 'romance1_11', type: 'image', source: require('./assets/stickers/romance1/romance1_11.png') },
    { id: 'romance1_12', type: 'image', source: require('./assets/stickers/romance1/romance1_12.png') },
    { id: 'white1_01', type: 'image', source: require('./assets/stickers/white1/white1_01.png') },
    { id: 'white1_02', type: 'image', source: require('./assets/stickers/white1/white1_02.png') },
    { id: 'white1_03', type: 'image', source: require('./assets/stickers/white1/white1_03.png') },
    { id: 'white1_04', type: 'image', source: require('./assets/stickers/white1/white1_04.png') },
    { id: 'white1_05', type: 'image', source: require('./assets/stickers/white1/white1_05.png') },
    { id: 'white1_06', type: 'image', source: require('./assets/stickers/white1/white1_06.png') },
    { id: 'white1_07', type: 'image', source: require('./assets/stickers/white1/white1_07.png') },
    { id: 'white1_08', type: 'image', source: require('./assets/stickers/white1/white1_08.png') },
    { id: 'white1_09', type: 'image', source: require('./assets/stickers/white1/white1_09.png') },
    { id: 'white1_10', type: 'image', source: require('./assets/stickers/white1/white1_10.png') },
    { id: 'white1_11', type: 'image', source: require('./assets/stickers/white1/white1_11.png') },
    { id: 'white1_12', type: 'image', source: require('./assets/stickers/white1/white1_12.png') }
  ],
  'Y2K/키치': [
    { id: 'y2k1_01', type: 'image', source: require('./assets/stickers/y2k1/y2k1_01.png') },
    { id: 'y2k1_02', type: 'image', source: require('./assets/stickers/y2k1/y2k1_02.png') },
    { id: 'y2k1_03', type: 'image', source: require('./assets/stickers/y2k1/y2k1_03.png') },
    { id: 'y2k1_04', type: 'image', source: require('./assets/stickers/y2k1/y2k1_04.png') },
    { id: 'y2k1_05', type: 'image', source: require('./assets/stickers/y2k1/y2k1_05.png') },
    { id: 'y2k1_06', type: 'image', source: require('./assets/stickers/y2k1/y2k1_06.png') },
    { id: 'y2k1_07', type: 'image', source: require('./assets/stickers/y2k1/y2k1_07.png') },
    { id: 'y2k1_08', type: 'image', source: require('./assets/stickers/y2k1/y2k1_08.png') },
    { id: 'y2k1_09', type: 'image', source: require('./assets/stickers/y2k1/y2k1_09.png') },
    { id: 'y2k1_10', type: 'image', source: require('./assets/stickers/y2k1/y2k1_10.png') },
    { id: 'y2k1_11', type: 'image', source: require('./assets/stickers/y2k1/y2k1_11.png') },
    { id: 'y2k1_12', type: 'image', source: require('./assets/stickers/y2k1/y2k1_12.png') },
    { id: 'y2k1_13', type: 'image', source: require('./assets/stickers/y2k1/y2k1_13.png') },
    { id: 'y2k1_14', type: 'image', source: require('./assets/stickers/y2k1/y2k1_14.png') },
    { id: 'y2k1_15', type: 'image', source: require('./assets/stickers/y2k1/y2k1_15.png') },
    { id: 'y2k1_16', type: 'image', source: require('./assets/stickers/y2k1/y2k1_16.png') },
    { id: 'y2k1_17', type: 'image', source: require('./assets/stickers/y2k1/y2k1_17.png') },
    { id: 'y2k1_18', type: 'image', source: require('./assets/stickers/y2k1/y2k1_18.png') },
    { id: 'y2k1_19', type: 'image', source: require('./assets/stickers/y2k1/y2k1_19.png') },
    { id: 'y2k1_20', type: 'image', source: require('./assets/stickers/y2k1/y2k1_20.png') },
    { id: 'y2k1_21', type: 'image', source: require('./assets/stickers/y2k1/y2k1_21.png') },
    { id: 'y2k1_22', type: 'image', source: require('./assets/stickers/y2k1/y2k1_22.png') },
    { id: 'y2k1_23', type: 'image', source: require('./assets/stickers/y2k1/y2k1_23.png') },
    { id: 'y2k1_24', type: 'image', source: require('./assets/stickers/y2k1/y2k1_24.png') },
    { id: 'y2k1_25', type: 'image', source: require('./assets/stickers/y2k1/y2k1_25.png') }
  ]
};

export const FONTS = [
  { id: 'System', name: '기본체' }, 
  { id: 'NanumSquareRoundR', name: '나눔스퀘어' },
  { id: 'ownglyph', name: '오운글리프' },
  { id: 'MemomentKkukkukk', name: '꾹꾹체' }
];

export const HIGHLIGHTERS = [
  { id: 'neon_pink', color: 'rgba(255, 20, 147, 0.45)', name: '쨍한핑크', type: 'color' },
  { id: 'neon_green', color: 'rgba(57, 255, 20, 0.45)', name: '쨍한초록', type: 'color' },
  { id: 'neon_yellow', color: 'rgba(255, 255, 0, 0.5)', name: '쨍한노랑', type: 'color' },
  { id: 'neon_orange', color: 'rgba(255, 165, 0, 0.45)', name: '쨍한주황', type: 'color' },
  { id: 'pastel_blue', color: 'rgba(174, 198, 207, 0.55)', name: '파스텔블루', type: 'color' },
  { id: 'pastel_purple', color: 'rgba(221, 160, 221, 0.55)', name: '파스텔보라', type: 'color' },
  { id: 'pastel_mint', color: 'rgba(184, 242, 230, 0.55)', name: '파스텔민트', type: 'color' },
  
  // 💡 패턴들도 ./assets/ 로 수정 완료!
  { id: 'dot1', texture: require('./assets/patterns/dot1.png'), name: '도트1', type: 'pattern', design: 'dot' },
  { id: 'dot2', texture: require('./assets/patterns/dot2.png'), name: '도트2', type: 'pattern', design: 'dot' },
  { id: 'dot3', texture: require('./assets/patterns/dot3.png'), name: '도트2', type: 'pattern', design: 'dot' },
  { id: 'dot4', texture: require('./assets/patterns/dot4.png'), name: '도트2', type: 'pattern', design: 'dot' },
  { id: 'hopi1', texture: require('./assets/patterns/hopi1.png'), name: '호피1', type: 'pattern', design: 'leopard' },
  { id: 'hopi2', texture: require('./assets/patterns/hopi2.png'), name: '호피2', type: 'pattern', design: 'leopard' },
  { id: 'hopi3', texture: require('./assets/patterns/hopi3.png'), name: '호피2', type: 'pattern', design: 'leopard' },
  { id: 'hopi4', texture: require('./assets/patterns/hopi4.png'), name: '호피2', type: 'pattern', design: 'leopard' },
];